# Locator's configuration file

---

#google API browser key, generated for curloptReferer
key: AIzaSyCJ5VaEENCa_rcDSZ0Tzrfs1rNfd5xxzpk
#cache files datetime format
cacheDateFormat: YmdHis
#cache expiration time in seconds
cacheTimeSec: 3600
#referer page that will be set during API call
curloptReferer: http://127.0.0.1:8080/locator.php
#cURL connection timeout
curloptConnectTimeoutSec: 30
#google places TEXTSEARCH api URL
googleTextSearch: https://maps.googleapis.com/maps/api/place/textsearch